### ISSUE TITLE
 "Contains" function in a wide world bounds doesn't work.

### ISSUE THREAD

**Issue by jose-nunez** [tubalmartin/spherical-geometry#1]
Hi. Thank you very much for the library. I'm using it in combination with leaflet js.
I have this LatLngBounds created with coordinates:
swLat => -85.051128779807
neLat => 85.051128779807
swLng => 180
neLng => -180
That is almost a world wide zone. 'Contains' function is giving me false to any coordinates I test on.

Thank you!

**Comment by tubalmartin** [comment]
Does the Google Maps API return the expected value with your settings?

**Comment by jose-nunez** [comment]
I'm using Leaflet.js and it is giving the right values for the same LatLngBounds object.
This is the only one who is giving me problems on your library, then I used and special case for it, always returning true, because it covers the whole globe.

**Comment by tubalmartin** [comment]
Already fixed! Thank you for reporting and sorry for the delay :(

**Comment by jose-nunez** [comment]
Sweet. Thank you very much!
